auth_methods:
  - tag: irma
    name: Gebruik je IRMA app
    image_path: /static/irma.svg
    start: https://irma.auth.id-contact.nl
  - tag: digid
    name: Gebruik DigiD
    image_path: /static/digid.svg
    start: https://digid.auth.id-contact.nl

comm_methods:
  - tag: call
    name: Bellen
    image_path: /static/phone.svg
    start: https://irma.auth.id-contact.
    purposes: [report_move, request_passport, request_permit]
  - tag: chat
    name: Chatten
    image_path: /static/chat.svg
    start: https://digid.auth.id-contact.n
    purposes: [report_move, request_permit]