server_url: http://core:8000
internal_secret: sample_secret_12345678901234567890

auth_methods:
  - tag: irma
    name: Gebruik je IRMA app
    image_path: /static/irma.svg
    start: http://auth-irma:8000
  - tag: digid
    name: Gebruik DigiD
    image_path: /static/digid.svg
    start: http://auth-test:8000

comm_methods:
  - tag: call
    name: Bellen
    image_path: /static/phone.svg
    start: http://comm-test:8000
  - tag: chat
    name: Chatten
    image_path: /static/chat.svg
    start: http://comm-matrix-bot:3000

purposes:
  - tag: report_move
    attributes:
      - email
    allowed_auth:
      - "*"
    allowed_comm:
      - call
      - chat
  - tag: request_permit
    attributes:
      - email
    allowed_auth:
      - irma
      - digid
    allowed_comm:
      - "*"
  - tag: request_passport
    attributes:
      - email
    allowed_auth:
      - "*"
    allowed_comm:
      - call
