auth_methods:
  - tag: irma
    name: Gebruik je IRMA app
    image_path: /static/irma.svg
    start: http://auth-irma:8000
  - tag: digid
    name: Gebruik DigiD
    image_path: /static/digid.svg
    start: http://auth-test:8000

comm_methods:
  - tag: call
    name: Bellen
    image_path: /static/phone.svg
    start: http://comm-matrix-bot:3000
    purposes: [report_move, request_passport, request_permit]
  - tag: chat
    name: Chatten
    image_path: /static/chat.svg
    start: http://comm-matrix-bot:3000
    purposes: [report_move, request_permit]

purpose_attributes:
  report_move:
    - email
  request_passport:
    - email
  request_permit:
    - email
